import type { NextPage } from 'next';
import Head from 'next/head';

import { StickyHeader } from '@/components/StickyHeader';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StickyHeader />
      <section>
        <div className="banner">
          <div className="banner-slide" style={{ backgroundImage: `url( 'images/beach-walking.jpg' )` }}>
            <div className="container-wide">
              <div className="banner-slide__content">
                <h1 className="main-title heading__title">Aroha mai, aroha atu</h1>
                <p className="title-paragraph inner-section-margin">With Grace & Aroha, parenting can take on a whole new lens. One of understanding, patience, resilience, and most of all kindness to yourself as a parent.</p>
                <a href="contact" className="btn btn-secondary banner-btn">
                  Get in touch
                </a>
              </div>
            </div>
            <div className="banner__tint"></div>
          </div>
        </div>
      </section>
      <section className="container primary-content section-margin">
        <h2 className="section-margin title-heading">Welcome to Grace & Aroha</h2>
        <p className="inner-section-margin">
          At Grace & Aroha Ltd, our approach to care and learning is indeed grace and aroha; we strive to respectfully meet the needs of children and whānau with care and love, while recognising the potential each child has and supporting their
          natural growth and development. Children need to be trusted, to lead, play, explore, grow. Whānau should be supported with care as they raise their children. The three underlying principles of our kaupapa are love, care and respect.
        </p>
        <p className="inner-section-margin">
          Neuroscience tells us that the brain needs to be in a state of well-being before it can be ready for learning. The warm environment of love and genuine connection we model at Grace & Aroha Ltd enhances every child's learning and
          development.{' '}
        </p>
        <p className="inner-section-margin">
          When we show respect to children through listening and acknowledging them, their thoughts and feelings, they learn their worth and can begin to understand that every person is deserving of respect. We will share our lens of viewing the
          child in a holistic way, using love, care and respect providing a strong, healthy foundation for them to build all other relationships throughout their life.{' '}
        </p>
        <p className="inner-section-margin">We can guide you to understand this Kaupapa so that you gain confidence in your parenting and empower your child to be the confident and competent person they were born to be.</p>

        <a href="contact" className="btn banner-button-secondary section-margin">
          Call us now
        </a>
      </section>

      {/* <section className="positioning section-margin">
    <div className="row g-0">
      <div className="col-md-6 backgrounds">
        <a href="our-story" className="grid__block js-tilt">
          <div className="content tint">
            <img className="image-scale" src="./images/rocks-min.jpg">
            <h3 className="on-top">Our Story</h3>
          </div>
        </a>
      </div>
      <div className="col-md-6 backgrounds">
        <a href="services" className="grid__block js-tilt">
          <div className="content tint">
            <img className="image-scale" src="images/abd.jpg">
            <h3 className="on-top">Services</h3>
          </div>
        </a>
      </div>
      <div className="col-md-6 backgrounds">
        <a href="find-childcare" className="grid__block js-tilt">
          <div className="content tint">
            <img className="image-scale" src="./images/rock-min.jpg">
            <h3 className="on-top">Find Childcare</h3>
          </div>
        </a>
      </div>
      <div className="col-md-6 backgrounds">
        <a href="contact" className="grid__block js-tilt">
          <div className="content tint">
            <img className="image-scale" src="images/j-floor.JPG">
            <h3 className="on-top">Contact Us</h3>
          </div>
        </a>
      </div>
    </div>
  </section>
  <section className="testimonials section-margin">
    <h2>Testimonials</h2>
    <div id="testimonials-carousel" className="carousel slide" data-bs-ride="carousel" data-bs-pause="hover" data-bs-interval="10000">
      <div className="carousel-inner">
        <div className="carousel-item active">
          <p>Jay has played a huge part in raising our two girls through work hours. If you are looking for a loving teacher that treats children with respect and kindness there is no need to look
            anywhere else. Jay is very knowledgeable in the latest techniques of early childhood development. When you’re unsure as a parent Jay always gives great advice on what to do in trying
            times. Above all else Jay always brings a sense of calm to everyday which gives further assurance that your children get the best and safest level of care. I highly recommend Jay Fowles at
            Grace and Aroha Educare.</p>
          <em>- Campbell and Candice Upperton</em>
        </div>
        <div className="carousel-item">
          <p>When meeting Jay, it was evident how passionate she was about childcare. What also shone through was her strong, genuine emphasis on what’s best for the individual child approach, that
            she fosters.
            Sending my little girl to Jay’s at home-based care was an easy decision, one I would make 100 times over. The love and care that Kennedy receives on a daily basis is what I would compare
            to sending her to a family member. Jay has not only been awesome for Kennedy but the extra support she provides to me as a mum has been priceless. Providing help and support comes second
            nature to her and I would now happily call her my friend.
            I would 100% recommend Grace and Aroha to anybody looking for childcare for their children. Kennedy often prefers to go to Jay’s than to stay home with Mum. That’s a testament in itself
            that I made the right choice for my daughter and our family.</p>
          <em>- Nicky Smith</em>
        </div>
        <div className="carousel-item">
          <p>As a Mum who just had my second baby, with a fly in, fly out husband - I needed alot of help in the evenings! Jay would come and help me with my newborn and toddler. Anything from
            bathing,
            settling, feeding, cleaning bottles or playing trucks with my toddler so I could eat dinner or shower! Jay had a lot of practical advice to offer too, coming from her experience as both a
            Mum and an educator. Having Jay's help and support for the weeks my husband was away was a huge relief and I am so grateful we were introduced!</p>
          <em>- Fiona Morgan</em>
        </div>
        <div className="carousel-item">
          <p>Such a great support!! Highly recommend Jay. She has helped me so much over the years with my kids. My son wouldn't be self soothing to sleep without her help!!</p>
          <em>- Ashleigh</em>
        </div>
        <div className="carousel-item">
          <p>My guardian angel when it comes to helping me with my kids. The baby whisper and generally the most amazing women with babies and children. I highly recommend Jay! 🙌🙌🙌🙌 </p>
          <em>- Nicky</em>
        </div>
        <div className="carousel-item">
          <p>Jay offered great information and advice on sleeping but the key was that she helped me see Alex's daily life, naps and nights holistically. By changing how I fed, comforted and even
            entertained him, I was able to help him self soothe and sleep on his own quite easily. I now have a better understanding of what my baby is capable of on his own and what he needs from
            his sleep time.</p>
          <p>The most important aspect of Jay's help has been giving me confidence in myself as a parent. I am an overthinker and for me, Jay calmed my approach. I asked her one million questions,
            and she answered them all, but bit by bit I could see that my constant stress and consternation over sleep patterns and nap times was actually a problem, and her slower, gentler
            approach has destressed me and my baby into more independence for both of us.</p>
          <em>- Lyndsay</em>
        </div>
        <div className="carousel-item">
          <p>Jay has a wonderful calm nature and a really trusting energy about her. After just a few minutes with her, I knew that she wasnt here to judge our parenting, or make us feel observed,
            or that anything we were doing was wrong. She just sat with me and wanted to get to know me and our family and some of the areas we felt like we could do with some support in.</p>
          <em>- Hannah and Elliot</em>
        </div>

      </div>
      <button className="carousel-control-prev carousel-fixings" type="button" data-bs-target="#testimonials-carousel" data-bs-slide="prev">&#10094;
      </button>
      <button className="carousel-control-next carousel-fixings" type="button" data-bs-target="#testimonials-carousel" data-bs-slide="next">&#10095;
      </button>
    </div>
    <p className="btn-container-mobile"><a className="btn banner-button-secondary" href="testimonials">View more</a></p>
  </section>
  <section className="padding">
    <div className="row g-0">
      <div className="col-lg-6 margining">
        <img className="bd-placeholder-img" width="140" height="140" src="images/kaupapa.png">
        <h2 className="heading-section">Kaupapa</h2>
        <p>Our role-modelling of love, care and respect with our children provides a strong, healthy foundation for them to build all other relationships throughout their life.</p>
        <p><a className="btn banner-button-secondary centering" href="our-story">View details &raquo;</a></p>
      </div>
      <div className="col-lg-6 margining">
        <img className="bd-placeholder-img" width="140" height="140" src="images/hands.png">
        <h2 className="heading-section">Whānau</h2>
        <p>Whānau should be supported with care as they raise their children. The three underlying principles of our kaupapa are love, care and respect.</p>
        <p><a className="btn banner-button-secondary centering" href="services">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <!-- <div className="col-lg-4 margining">
        <img className="bd-placeholder-img" width="140" height="140" src="images/rainbow-trans.png" role="img" width="100%" height="100%" fill="#777" /></img>
        <h2 className="heading-section">Kaiako</h2>
        <p>Through our home-based care and education service, as well as other support services, our goal is to create a community of learners, learning with and from each other.</p>
        <p><a className="btn banner-button-secondary" href="work-with-us">View details &raquo;</a></p>
      </div> -->
    </div>
  </section> */}
    </div>
  );
};

export default Home;
